Repository danielkull/capp, pull requests merged in 2023-08, with the labels that each got.

#310 Profile settings data editable
  src/components/main-component/expand-menu-components/CarDataTable.vue
  src/components/main-component/expand-menu-components/DeleteLogQuestion.vue
  src/components/main-component/expand-menu-components/UserDatesTable.vue
  src/components/main-component/expand-site-cards/CarDataExpandCard.vue
  src/components/main-component/expand-site-cards/ConfirmationExpandCard.vue
  src/components/main-component/expand-site-cards/UserDataExpandCard.vue
  src/stores/useAuthenticationStore.js
  src/stores/useCarStore.js
  src/views/MainPageView.vue
  src/views/UserProfileView.vue
Labels: enhancement, before merge, content

#311 fix: password validation now works in sign in
  src/views/LogView.vue
Labels: bug

#313 fix cssbugs
  src/components/FilterDropDown.vue
  src/components/main-component/SmallCarCard.vue
Labels: bug

#319 fix: github icon link leads now to the respective profil
  src/components/main-component/expand-menu-components/TeamSingle.vue
Labels: bug, before merge
