Repository danielkull/capp, pull requests merged in 2023-06, with the labels that each got.

#4 add: reset.css global.css colors
  src/styles/color-properties.css
  src/styles/global.css
  src/styles/reset.css
Labels: enhancement

#17 feat: adds router and stefans view
  package-lock.json
  package.json
  src/App.vue
  src/components/HelloWorld.vue
  src/main.js
  src/router/index.js
  src/views/AboutView.vue
  src/views/HomeView.vue
  src/views/StefansView.vue
Labels: enhancement

#19 fix: stefans view is visible and adds @ alias for path finding
  src/router/index.js
  src/views/StefansView.vue
  vite.config.js
Labels: bug

#28 feat: adds input Component and example DanielsView
  src/App.vue
  src/components/input-elements/InputText.vue
  src/router/index.js
  src/views/DanielsView.vue
Labels: enhancement

#42 feat: add input elemnts on LogIn Page, help btns
  src/App.vue
  src/components/input-elements/InputText.vue
  src/styles/color-properties.css
  src/views/LogView.vue
Labels: content

#53 40 create passwort toggle
  src/App.vue
  src/components/input-elements/InputText.vue
  src/views/LogView.vue
Labels: before merge

#48 feat: add mainpageview-mobile and desktop
  src/App.vue
  src/router/index.js
  src/styles/color-properties.css
  src/views/LogView.vue
  src/views/MainPageView.vue
Labels: Merge Conflicts

#57 feat: add icons
  src/assets/Car-Types/Bus.svg
  src/assets/Car-Types/Cabrio.svg
  src/assets/Car-Types/Kleinwagen.svg
  src/assets/Car-Types/Pickup.svg
  src/assets/Car-Types/Suv.svg
  src/assets/Car-Types/Transporter.svg
  src/assets/Fuel-Types/Autogas.svg
  src/assets/Fuel-Types/Diesel.svg
  src/assets/Fuel-Types/Electro.svg
  src/assets/Fuel-Types/Gas.svg
  src/assets/Fuel-Types/Hybrid.svg
  src/assets/Fuel-Types/Wasserstoff.svg
  src/assets/Trunk-Types/L-trunk.svg
  src/assets/Trunk-Types/M-trunk.svg
  src/assets/Trunk-Types/S-trunk.svg
  src/assets/Trunk-Types/XL-trunk.svg
  src/assets/Trunk-Types/XXL-trunk.svg
  src/assets/different-types/Car-symbol.svg
  src/assets/different-types/Isofix.svg
  src/assets/different-types/Raucher.svg
  src/assets/different-types/Tiere.svg
Labels: content

#55 feat: add fonts
  src/Fonts/Bodoni/BodoniModa_28pt-Medium.woff2
  src/Fonts/Bodoni/BodoniModa_72pt-Bold.woff2
  src/Fonts/roboto/Roboto-Black.woff2
  src/Fonts/roboto/Roboto-Bold.woff2
  src/Fonts/roboto/Roboto-Italic.woff2
  src/Fonts/roboto/Roboto-Light.woff2
  src/Fonts/roboto/Roboto-LightItalic.woff2
  src/Fonts/roboto/Roboto-Medium.woff2
  src/Fonts/roboto/Roboto-Regular.woff2
  src/styles/global.css
  src/views/MainPageView.vue
Labels: content
