Repository danielkull/capp, pull requests merged in 2023-07, with the labels that each got.

#68 chore: clear App.vue into KirstensView
  src/App.vue
  src/components/input-elements/InputText.vue
  src/router/index.js
  src/views/KirstensView.vue
Labels: before merge

#70 51 commentar section in usersprofile
  src/App.vue
  src/components/messenger/AverageRating.vue
  src/components/messenger/CustomerReviews.vue
  src/components/messenger/RatingBar.vue
  src/components/messenger/RatingIcon.vue
  src/views/LogView.vue
  src/views/UserProfileView.vue
Labels: before merge, Merge Conflicts

#61 41 function for elements
  src/components/input-elements/InputText.vue
  src/views/LogView.vue
Labels: content, Merge Conflicts

#74 feat: add popout for user kommentar
  src/assets/different-types/Seat.svg
  src/components/UserEvaluation.vue
  src/styles/color-properties.css
  src/styles/global.css
  src/views/StefansView.vue
Labels: content, Merge Conflicts

#91 fix: corrects typos and wrong naming, includes InputText.vue introduc…
  src/components/input-elements/InputText.vue
  src/views/DanielsView.vue
Labels: bug, plain text

#97 chore: fotn-family angepasst für jedne Typ
  src/Fonts/roboto/Roboto-Thin.woff2
  src/styles/global.css
  src/views/UserProfileView.vue
Labels: content

#98 feat: add icons, fix icons, add card Version 1
  src/assets/different-types/geo-alt-fill (1).svg
  src/assets/different-types/geo-alt.svg
  src/assets/different-types/plus.svg
  src/components/SmallCarCard.vue
  src/components/icon-type/DifferentTypes.vue
  src/components/icon-type/IconType.vue
  src/components/icon-type/TrunkType.vue
  src/components/icon-type/fuelType.vue
  src/styles/color-properties.css
  src/views/MainPageView.vue
  src/views/StefansView.vue
Labels: content

#104 feat: add button componente
  src/components/input-elements/Button.vue
  src/views/StefansView.vue
Labels: content

#95 20 pinia stage management installieren
  package-lock.json
  package.json
  src/main.js
  src/stores/userStateStorage.js
  src/views/DanielsView.vue
Labels: enhancement, before merge

#109 chore: implements changing of current date
  src/components/Calender.vue
Labels: content

#111 105 dark mode test 2
  index.html
  src/App.vue
  src/assets/menue-icons/cloud-moon-fill.svg
  src/assets/menue-icons/cloud-sun-fill.svg
  src/components/input-elements/DarkModeButton.vue
  src/styles/color-properties.css
  src/styles/global.css
  src/views/StefansView.vue
Labels: content

#119 chore: fix bug in login card- add backbuttopn componente
  src/components/input-elements/BackButton.vue
  src/components/input-elements/Button.vue
  src/views/LogView.vue
Labels: bug

#123 121 customproperties anpassen main page
  src/App.vue
  src/components/SmallCarCard.vue
  src/components/cars-components/CarCard.vue
  src/components/icon-type/DifferentTypes.vue
  src/components/icon-type/IconType.vue
  src/components/icon-type/TrunkType.vue
  src/components/icon-type/fuelType.vue
  src/components/main-component/NavBar.vue
  src/components/main-component/NavMenue.vue
  src/styles/color-properties.css
  src/styles/global.css
  src/views/MainPageView.vue
Labels: bug, content, CleanUp

#134 chore: clear code Z: 379-382
  src/views/LogView.vue
Labels: CleanUp

#137 feat: add disabled class to button.vue
  src/components/input-elements/Button.vue
  src/styles/color-properties.css
Labels: content

#146 feat: dark mode checkbox compöonente
  src/components/input-elements/CheckBox.vue
  src/styles/color-properties.css
Labels: content

#140 feta: add accordion comöonente
  src/components/main-component/AccordionDefault.vue
  src/styles/color-properties.css
  src/views/StefansView.vue
Labels: content

#142 141 add darkmode userprofile
  src/components/icon-type/SeatIcons.vue
  src/components/messenger/CustomerReviews.vue
  src/components/messenger/RatingIcon.vue
  src/styles/color-properties.css
  src/styles/global.css
  src/views/UserProfileView.vue
Labels: bug, content, CleanUp

#133 112 single carcard component design an neuere version anpassen
  src/components/cars-components/CarCard.vue
  src/components/icon-type/IconSeatsCount.vue
  src/components/icon-type/IconType.vue
  src/components/icon-type/TrunkType.vue
  src/components/icon-type/fuelType.vue
  src/views/CarView.vue
  src/views/CarsView.vue
Labels: content

#156 feat: add accordion Usermenue
  src/assets/menue-icons/calendar3-week.svg
  src/assets/menue-icons/chat-right-dots.svg
  src/assets/menue-icons/clipboard2-check.svg
  src/assets/menue-icons/info-square.svg
  src/components/car-equipment/car-equipment.vue
  src/components/car-equipment/car-infos.vue
  src/components/input-elements/Button.vue
  src/components/input-elements/TextArea.vue
  src/components/main-component/CarOwnerAccordion.vue
  src/styles/color-properties.css
  src/views/StefansView.vue
  src/views/UserProfileView.vue
Labels: content

#163 feat:add faq componente
  src/components/main-component/NavBar.vue
  src/components/user-menue/FaqMenue.vue
  src/styles/color-properties.css
  src/views/StefansView.vue
Labels: content

#168 167 add icons combi and limousine
  src/assets/Car-Types/Bus.svg
  src/assets/Car-Types/Combi.svg
  src/assets/Car-Types/Limousine.svg
  src/components/Calendar.vue
  src/components/icon-type/IconType.vue
  src/components/input-elements/Button.vue
  src/components/main-component/CarOwnerAccordion.vue
  src/components/messenger/CustomerReviews.vue
  src/views/UserProfileView.vue
Labels: content

#170 118 user authentication anbindung erstellen
  src/App.vue
  src/components/input-elements/InputText.vue
  src/components/test-user-management/LoggedIn.vue
  src/components/test-user-management/PageEntry.vue
  src/router/index.js
  src/stores/useAuthenticationStore.js
  src/stores/useCarStore.js
  src/views/TestUserManagementView.vue
Labels: before merge

#171 feat FAQ für Owner wurde eingefügt
  src/components/user-menue/FaqMenue.vue
Labels: before merge

#172 chore: removes Copys from App and UserProifleView
  src/AppCopy.vue
  src/views/UserProfileViewCopy.vue
Labels: before merge, CleanUp

#173 chore: removes not used about page
  src/App.vue
  src/router/index.js
  src/views/AboutView.vue
Labels: before merge, CleanUp

#174 166 inputtextvue komponente erweitern
  src/components/input-elements/Button.vue
  src/components/input-elements/InputText.vue
  src/components/input-elements/SelectDropDown.vue
  src/components/input-elements/TextArea.vue
  src/views/DanielsView.vue
Labels: enhancement, before merge, content

#183 feat: add Dm to buttons and LogIn page
  src/components/input-elements/Button.vue
  src/styles/color-properties.css
  src/views/LogView.vue
Labels: content

#185 153 benutzer der app sollen nur ihre eigenen benutzerdaten anpassen und verändern können
  public/_redirects
  src/components/test-user-management/LoggedIn.vue
Labels: before merge, content

#186 chore: korrgieren der Units der input fields, Passwort inner text ang…
  src/components/input-elements/InputText.vue
  src/views/LogView.vue
Labels: content, CleanUp

#191 180 authentifizierung in logviewvue einbauen
  src/components/Calendar.vue
  src/components/UserQuestionMenue.vue
  src/components/input-elements/Button.vue
  src/components/input-elements/InputText.vue
  src/components/test-user-management/LoggedIn.vue
  src/router/index.js
  src/stores/useAuthenticationStore.js
  src/views/AddNewCarView.vue
  src/views/CarView.vue
  src/views/CarsView.vue
  src/views/LogView.vue
  src/views/UserProfileView.vue
Labels: enhancement, before merge, content, CleanUp

#188 chore: add DM Back Button, fix properties Log In vue
  src/components/input-elements/BackButton.vue
  src/components/input-elements/Button.vue
  src/styles/color-properties.css
  src/views/LogView.vue
Labels: content, CleanUp

#194 refactor: rebuild the main with the correct SmallCarCard component an…
  src/App.vue
  src/components/SmallCarCard.vue
  src/components/cars-components/CarCard.vue
  src/components/input-elements/CheckBox.vue
  src/components/main-component/CarOwnerAccordion.vue
  src/components/main-component/MainMenue.vue
  src/components/main-component/SmallCarCard.vue
  src/components/main-component/expand-menu-components/MessageOptionMenue.vue
  src/router/index.js
  src/views/CarView.vue
  src/views/CarsView.vue
  src/views/MainPageView.vue
Labels: before merge, content, CleanUp

#195 feat:add User Data in userdatestable
  src/components/main-component/expand-menu-components/MessageOptionMenue.vue
  src/components/main-component/expand-menu-components/UserDatesTable.vue
  src/components/main-component/expand-site-cards/UserDataExpandCard.vue
  src/styles/global.css
Labels: content

#202 chore: removes testpurpose userStateStorage from app
  src/stores/userStateStorage.js
  src/views/DanielsView.vue
Labels: before merge, CleanUp

#204 201 feat faq owner user in expand cards code korrigieren
  src/components/main-component/expand-menu-components/FaqSingleQuestion.vue
  src/components/main-component/expand-site-cards/FaqClientExpandCard.vue
  src/components/main-component/expand-site-cards/FaqOwnerExpandCard.vue
  src/views/MainPageView.vue
Labels: content

#211 feat: add impressum and Dataschuitz, add Teamsite-Teamcards
  src/assets/logos/CSS3_logo.svg.png
  src/assets/logos/Figma-logo.svg
  src/assets/logos/HTML5_logo_and_wordmark.svg.png
  src/assets/logos/JavaScript_logo_2.svg.png
  src/assets/logos/Miro.png
  src/assets/logos/Pinia.svg
  src/assets/logos/Vue.js_Logo_2.svg.png
  src/assets/logos/procerate.png
  src/assets/logos/sass-1-logo.png
  src/assets/logos/supabase-logo-DCC676FFE2-seeklogo.com.png
  src/assets/menue-icons/github.svg
  src/components/main-component/expand-menu-components/FaqSingleQuestion.vue
  src/components/main-component/expand-menu-components/ImpressumdatSecurText.vue
  src/components/main-component/expand-menu-components/TeamSingle.vue
  src/components/main-component/expand-site-cards/DataSafetyExpandCard.vue
  src/components/main-component/expand-site-cards/ImpressumExpandCard.vue
  src/components/main-component/expand-site-cards/TeamExpandCard.vue
  src/components/main-component/expand-site-cards/UseExpandCard.vue
  src/styles/color-properties.css
Labels: content

#207 87 text eingabefelder im fragebogen durch inputtext component ersetzen
  src/components/FilterDropDown.vue
  src/components/UserQuestionMenue.vue
  src/components/input-elements/InputText.vue
  src/components/input-elements/SelectDropDown.vue
  src/views/AddNewCarView.vue
  src/views/KirstensView.vue
Labels: content

#219 feat: add delete und logout link + scren
  src/components/main-component/MainMenue.vue
  src/components/main-component/NavMenue.vue
  src/components/main-component/expand-menu-components/DeleteLogQuestion.vue
  src/components/main-component/expand-menu-components/FaqSingleQuestion.vue
  src/components/main-component/expand-menu-components/UserDatesTable.vue
  src/components/main-component/expand-site-cards/CarDataExpandCard.vue
  src/components/main-component/expand-site-cards/DataSafetyExpandCard.vue
  src/components/main-component/expand-site-cards/DeleteExpandCard.vue
  src/components/main-component/expand-site-cards/FaqClientExpandCard.vue
  src/components/main-component/expand-site-cards/FaqOwnerExpandCard.vue
  src/components/main-component/expand-site-cards/ImpressumExpandCard.vue
  src/components/main-component/expand-site-cards/LogoutEpandCard.vue
  src/components/main-component/expand-site-cards/MessageSettingsExpandCard.vue
  src/components/main-component/expand-site-cards/TeamExpandCard.vue
  src/components/main-component/expand-site-cards/UseExpandCard.vue
  src/components/main-component/expand-site-cards/UserDataExpandCard.vue
  src/styles/color-properties.css
  src/views/MainPageView.vue
Labels: content

#230 214 filter logik in filterdropdown komponente einbauen
  src/components/FilterDropDown.vue
  src/components/UserQuestionMenue.vue
Labels: enhancement

#232 231 messenger platzhalter
  src/assets/menue-icons/mic-fill.svg
  src/assets/menue-icons/person-circle (1).svg
  src/assets/menue-icons/pin-angle-fill.svg
  src/assets/menue-icons/send-fill.svg
  src/components/main-component/NavBar.vue
  src/components/messenger/messenger-placeholder/MessageChatWindow.vue
  src/components/messenger/messenger-placeholder/MessagePin.vue
  src/components/messenger/messenger-placeholder/MessageSingle.vue
  src/components/messenger/messenger-placeholder/MessengerWindow.vue
  src/styles/color-properties.css
Labels: content

#238 chore: add css
  src/components/input-elements/DropDownTwoColumns.vue
  src/components/input-elements/InputText.vue
  src/components/input-elements/TextAreaWithoutButton.vue
  src/components/main-component/expand-site-cards/BookingExpandCard.vue
  src/components/messenger/messenger-placeholder/MessengerWindow.vue
  src/styles/global.css
Labels: content

#245 244 autobilder lokal speichern
  src/assets/img/car-img/02-renault-twingo.jpg
  src/assets/img/car-img/03-opel-vectra.jpg
  src/views/HomeView.vue
Labels: content

#247 243 anpassung filter menue
  src/components/FilterDropDown.vue
  src/components/UserQuestionMenue.vue
  src/components/input-elements/CheckBox.vue
  src/styles/color-properties.css
  src/styles/global.css
  src/views/MainPageView.vue
Labels: bug, content, CleanUp

#246 189 daten nach supabase wenn user owner fragebogen ausgefuellt
  src/App.vue
  src/components/UserQuestionMenue.vue
  src/components/main-component/expand-menu-components/QuestionMenuExpand.vue
  src/router/index.js
  src/views/LogView.vue
  src/views/UserQuestionView.vue
Labels: content

#265 feat:fix bug in header chat
  src/components/main-component/NavBar.vue
  src/styles/color-properties.css
Labels: bug

#262 chore: adds back to main page functionality in car-user-profil
  src/views/UserProfileView.vue
Labels: content

#267 fix: fixs bug of #235
  src/components/main-component/MessageMenu.vue
  src/views/LogView.vue
  src/views/MainPageView.vue
Labels: content

#269 feat: dark mode bt anegapsst
  src/App.vue
  src/components/input-elements/DarkModeButton.vue
  src/components/main-component/MainMenue.vue
  src/views/LogView.vue
Labels: content

#271 chore: unnötige Custom properties gelöhsct
  src/components/main-component/FooterImpressum.vue
  src/components/main-component/MainMenue.vue
  src/styles/color-properties.css
  src/styles/global.css
Labels: CleanUp

#272 236 give log button in app functionality and activate auth movement control
  src/App.vue
  src/components/main-component/MainMenue.vue
  src/components/main-component/MessageMenu.vue
  src/components/main-component/NavBar.vue
  src/components/not-in-build/AddNewCarView.vue
  src/components/test-user-management/LoggedIn.vue
  src/components/test-user-management/PageEntry.vue
  src/router/index.js
  src/stores/useAuthenticationStore.js
  src/views/CalenderView.vue
  src/views/DanielsView.vue
  src/views/ErrorPageview.vue
  src/views/HomeView.vue
  src/views/KirstensView.vue
  src/views/LogView.vue
  src/views/MainPageView.vue
  src/views/StefansView.vue
  src/views/TestUserManagementView.vue
Labels: before merge, content, CleanUp

#276 268 weitere autobilder bearbeiten und lokal speichern
  src/assets/img/car-img/01-vw-polo.jpg
  src/assets/img/car-img/03-opel-vectra.jpg
  src/assets/img/car-img/04-ford-sierra-xr4.jpg
  src/assets/img/car-img/05-vw-bully-836060.jpg
  src/assets/img/car-img/05-vw-bully-836086.jpg
  src/assets/img/car-img/06-mazda-mx5-1840414.jpg
  src/assets/img/car-img/06-mazda-mx5-3546782.jpg
  src/assets/img/car-img/07-porsche-cayenne-3282479.jpg
  src/assets/img/car-img/07-porsche-cayenne-4924287.jpg
  src/assets/img/car-img/08-mercedes-amg-gt-4-door-coupe.jpg
  src/assets/img/car-img/09-vw-golf-2805022.jpg
  src/assets/img/car-img/09-vw-golf-3699510.jpg
Labels: content

#279 chore:foxbugs
  src/components/icon-type/DifferentTypes.vue
  src/components/input-elements/Button.vue
  src/components/input-elements/DarkModeButton.vue
  src/components/input-elements/InputText.vue
  src/components/main-component/FooterImpressum.vue
  src/components/main-component/MainMenue.vue
  src/components/main-component/MessageMenu.vue
  src/components/main-component/NavBar.vue
  src/components/main-component/expand-menu-components/TeamSingle.vue
  src/components/messenger/MessageBox.vue
  src/components/messenger/messenger-placeholder/MessagePin.vue
  src/components/messenger/messenger-placeholder/MessageSingle.vue
  src/styles/color-properties.css
  src/styles/global.css
  src/views/LogView.vue
  src/views/MainPageView.vue
Labels: bug

#282 277 is smoker und has isofix spalte in cars tabelle in smallcarcard und mainpageview integrieren
  src/components/main-component/CarOwnerAccordion.vue
  src/components/main-component/SmallCarCard.vue
  src/views/MainPageView.vue
  src/views/UserProfileView.vue
Labels: before merge, content

#287 keine bugs gefunden
  src/components/UserQuestionMenue.vue
  src/components/input-elements/DarkModeButton.vue
Labels: bug

#289 241 filterfunktion mit auto liste verbinden
  src/components/FilterDropDown.vue
  src/views/MainPageView.vue
Labels: content

#291 refactor: fixes navbar menue, now only one view is opend
  src/components/main-component/NavBar.vue
  src/components/main-component/expand-menu-components/TeamSingle.vue
Labels: bug, before merge

#294 refactor: fixs navButton new bug, custom properties radio button, set…
  src/components/UserQuestionMenue.vue
  src/components/input-elements/RadioButton.vue
  src/components/main-component/NavBar.vue
Labels: content

#297 fix css
  src/components/UserQuestionMenue.vue
  src/components/icon-type/DifferentTypes.vue
  src/components/icon-type/IconType.vue
  src/components/icon-type/SeatIcons.vue
  src/components/icon-type/TrunkType.vue
  src/components/icon-type/fuelType.vue
  src/components/input-elements/InputText.vue
  src/components/input-elements/SelectDropDown.vue
  src/components/main-component/SmallCarCard.vue
  src/styles/reset.css
  src/views/LogView.vue
  src/views/UserProfileView.vue
Labels: bug

#298 chore: fix css
  src/components/input-elements/InputText.vue
  src/components/main-component/FooterImpressum.vue
  src/styles/color-properties.css
Labels: bug, CleanUp

#299 237 datum logik beim buchungsanfrage muss erstellt werden
  src/components/main-component/MainMenue.vue
  src/components/main-component/expand-menu-components/DeleteLogQuestion.vue
  src/components/main-component/expand-menu-components/UserDatesTable.vue
  src/components/main-component/expand-site-cards/BookingConfirmationExpandCard.vue
  src/components/main-component/expand-site-cards/BookingExpandCard.vue
  src/components/main-component/expand-site-cards/LogoutExpandCard.vue
  src/stores/useGlobalStateStore.js
  src/views/MainPageView.vue
  src/views/UserProfileView.vue
Labels: bug, before merge, content, CleanUp
